version: '3'

services:
  db-container:
    image: shinobi881/getmusiclive-db-container:latest
    ports:
      - 6000:5432
  
  db-middleware:
    image: shinobi881/getmusiclive-database:latest
    volumes: 
      - ./:/usr/src/app
    links:
      - db-container
    depends_on:
      - db-container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: ["npm run serve"]
    
  getmusiclive-server:
    image: shinobi881/getmusiclive-server:latest
    links:
      - db-middleware
    depends_on:
      - db-middleware

  getmusiclive-client:
    image: shinobi881/getmusiclive-client:latest
    ports: 
      - 80:80
    links:
      - getmusiclive-server
    depends_on:
      - getmusiclive-server
      sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.14.0/docker-compose-$(uname -s)-$(uname -m)"

