version: '3'

services:
  db-container:
    image: shinobi881/getmusiclive-db-container:latest
    ports:
      - 6000:5432
  
  db-middleware:
    image: shinobi881/getmusiclive-database:latest
    build: ./
    volumes: 
      - ./:/usr/src/app
    links:
      - db-container
    depends_on:
      - db-container
    command: ["./wait-for-it.sh", "db-container:5432", "--", "npm run serve"]
    
  getmusiclive-server:
    image: shinobi881/getmusiclive-server:latest
    ports:
      - 80:80
    links:
      - db-middleware
    depends_on:
      - db-middleware
